<?php

// autoload.php @generated by Composer
//require_once  __DIR__ . '../composer/autoload_real.php';

require_once implode( DIRECTORY_SEPARATOR, [__DIR__, 'composer', 'autoload_real.php']);

return ComposerAutoloaderInit887fe7c3e68b8fe16f44cca87b7bba27::getLoader();

?>